server {
    listen 80;
    server_name basschreurs.nl www.basschreurs.nl;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name basschreurs.nl www.basschreurs.nl;

    ssl_certificate /etc/letsencrypt/live/basschreurs.nl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/basschreurs.nl/privkey.pem;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /littlelemon/static/ {
        alias /app/littlelemon_staticfiles/;
    }

    location /littlelemon/ {
        proxy_pass http://littlelemon-web-1:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}