# Generated by Django 5.2.3 on 2025-06-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='GuestbookMessage',
        ),
    ]
