# Generated by Django 5.2.3 on 2025-06-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_guestbookcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestbookComment',
        ),
    ]
